# Generated by Django 6.0.5 on 2026-05-12 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('building', models.CharField(max_length=80)),
                ('floor', models.CharField(blank=True, max_length=30)),
                ('capacity', models.PositiveIntegerField()),
                ('is_smart', models.BooleanField(default=False)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_computers', models.BooleanField(default=False)),
                ('is_exam_hall', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_image', models.ImageField(blank=True, upload_to='qr/classrooms/')),
            ],
            options={
                'ordering': ['building', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('credit_hours', models.PositiveSmallIntegerField(default=3)),
                ('requires_lab', models.BooleanField(default=False)),
                ('smart_classroom_needed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['student__username'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('duration_semesters', models.PositiveSmallIntegerField(default=4)),
            ],
            options={
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab'), ('tutorial', 'Tutorial'), ('exam', 'Exam')], default='lecture', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timeslot__day_of_week', 'timeslot__start_time', 'offering__course__code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='A', max_length=20)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('sessions_per_week', models.PositiveSmallIntegerField(default=3)),
                ('preferred_building', models.CharField(blank=True, max_length=80)),
                ('resource_requirements', models.JSONField(blank=True, default=list)),
                ('delivery_mode', models.CharField(choices=[('physical', 'Physical'), ('hybrid', 'Hybrid')], default='physical', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.course')),
            ],
            options={
                'ordering': ['course__code', 'section'],
            },
        ),
    ]
